### ISSUE TITLE
FE3Handler: Edition list corrections

### ISSUE THREAD

**Issue by Googulator** [gus33000/UUPMediaCreator#1]
Edition 0x4E is missing (it's unknown, but should be added as Unknown4E):
https://github.com/gus33000/UUPMediaCreator/blob/7fd44b428480dfd502febc43bbce2b0feff44a9c/src/WindowsUpdateLib.Shared/FE3Handler.cs#L1274

Edition 0x5F is misspelled (should read "Workgroup", not "Workground"): 
https://github.com/gus33000/UUPMediaCreator/blob/7fd44b428480dfd502febc43bbce2b0feff44a9c/src/WindowsUpdateLib.Shared/FE3Handler.cs#L1291

Edition 0x89 is missing:
https://github.com/gus33000/UUPMediaCreator/blob/7fd44b428480dfd502febc43bbce2b0feff44a9c/src/WindowsUpdateLib.Shared/FE3Handler.cs#L1332

Edition 0xAA is missing:
https://github.com/gus33000/UUPMediaCreator/blob/7fd44b428480dfd502febc43bbce2b0feff44a9c/src/WindowsUpdateLib.Shared/FE3Handler.cs#L1364

The following editions from winnt.h have no counterparts here, but I'm not sure if they are relevant, since they seem to be Xbox-specific:
`
#define PRODUCT_XBOX_SYSTEMOS                       0x000000C0
#define PRODUCT_XBOX_NATIVEOS                       0x000000C1
#define PRODUCT_XBOX_GAMEOS                         0x000000C2
#define PRODUCT_XBOX_ERAOS                          0x000000C3
#define PRODUCT_XBOX_HOSTOS                         0x000000C4
`

**Comment by gus33000** [comment]
Thanks! fixed
