### ISSUE TITLE
Latest (0.3.0.0) release gets flagged as a virus by Windows Defender.

### ISSUE THREAD

**Issue by midi1996** [gus33000/UUPMediaCreator#10]
No idea why it would trigger it but on my machines and several of my friends there were reports of this being a virus, I got builds from Actions tab and it did not trigger this.

![image](https://user-images.githubusercontent.com/4874726/105217617-641dff00-5b54-11eb-9130-e8097a94f9a5.png)

**Comment by gus33000** [comment]
Weird, will need to get checked with the defender team. This is a false positive. You'll notice that the archive in the release section is actually pulled from the actions too. See https://github.com/gus33000/UUPMediaCreator/actions/runs/494706495

**Comment by gus33000** [comment]
Hi, we released version 0.3.0.1 (https://github.com/gus33000/UUPMediaCreator/releases/tag/0.3.0.1), I ran a scan on my machine with windows defender and got no result. Could you please confirm if this is still the case?

![image](https://user-images.githubusercontent.com/3755345/106652054-39409b80-6595-11eb-9ecd-397b43c4d4bf.png)

**Comment by roy2021420** [comment]
Getting the same thing with uupdownloader. Now it's showing that it has been infected. Is this really a false positive I tried the latest version to download.

**Comment by midi1996** [comment]
![image](https://user-images.githubusercontent.com/4874726/106766853-8f1b4f00-663a-11eb-93e2-4e930dc8746f.png)

Edge is still complaining.

Windows Defender is now quiet (tried on both 20H2 and an insider build).

**Comment by riverar** [comment]
Submitted to Microsoft Security Intelligence folks for resolution. Stay tuned.

> Submission ID: 6d1f7e39-efbd-4778-aa1f-d3e84e890b20
> Status: Submitted
> Submitted: Feb 3, 2021 2:25:51 PM
> Last tested/affected Security intelligence version: 1.331.156.0

**Comment by riverar** [comment]
Should be resolved in definitions `1.331.169.0` and later. You can check for/pull down updates via Windows Update/Windows Security.

**Comment by gus33000** [comment]
Closing as the issue has been resolved
