### ISSUE TITLE
About the improvements UUPMediaCreator hopes to make

### ISSUE THREAD

**Issue by Gaoyifei1011** [gus33000/UUPMediaCreator#109]
关于UUPMediaCreator希望能够得到的改进
About the improvements UUPMediaCreator hopes to make

希望能更新一下UUPMediaCreator中提供的版本列表
Please update the version list provided with UUPMediaCreator
![屏幕截图 2022-04-01 235359](https://user-images.githubusercontent.com/49179966/161299895-8d42facf-b293-4311-ad49-54017346e978.jpg)
![image](https://user-images.githubusercontent.com/49179966/161300188-1b2a28c4-8572-4d2d-a0a5-8fcefed381b3.png)
目前Windows已经发布了Windows 11 22000和Dev 22H2 22581，但是UUPMediaCreator中的列表却显示的是旧的Windows 10版本21390，希望能够更新一下
Windows 11 22000 and Dev 22H2 22581 have been released, but the list in UUPMediaCreator shows the old Windows 10 version 21390, which is expected to be updated

版本界面选择Pro时，希望在下载选项提供创建其他版本的ISO脚本
When you select Pro on the version screen, you want to provide ISO scripts for creating other versions in the download option
![image](https://user-images.githubusercontent.com/49179966/161300228-7f7a798c-0e8c-484c-81ff-36e50abc4454.png)

**Comment by dongle-the-gadget** [comment]
The latest dev builds should be shown though?

**Comment by Gaoyifei1011** [comment]
Dev 版本可以看到，最新的22610，但是Windows 11正式版本22000却无法看到，而且列表显示的版本中，一些版本已经过期了，希望可以优化一下。
You can see the latest version 22610 for Dev, but you can't see the official version 22000 for Windows 11, and some of the versions in the list are out of date.
比如Windows 10 17763.1217(200505-1609)，Windows 10 18362.836(200505-1604)，Windows 10 19041.1415(211207-1656)，Windows 10 16299.15170928-1534)，Windows 10 17134.1(180410-1804)
![image](https://user-images.githubusercontent.com/49179966/166099960-119294af-dfeb-4a9c-9e33-767c6420e153.png)

**Comment by dongle-the-gadget** [comment]
Looks like CU support still hasn't been included with the latest release so you would just be getting 22000.1 either case.

**Comment by Gaoyifei1011** [comment]
> Looks like CU support still hasn't been included with the latest release so you would just be getting 22000.1 either case.

![image](https://user-images.githubusercontent.com/49179966/166104939-ad3960c9-28fc-4fe1-a713-fa77f9204eec.png)
然而在该列表中22000.1并没有出现，我个人认为应该对目前Windows的版本进行一个划分，就像UUP DUMP官方划分的那样，给一个直观的选择，而不是像现在这样杂乱。
However, 22000.1 does not appear in this list, and I personally think that a division should be made for the current version of Windows, just like the official division of UUP DUMP, giving an intuitive choice, rather than being cluttered as it is now.
