### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cl-ement05** [gus33000/UUPMediaCreator#17]
Could you please make a documentation ? Because for people unfamiliar with C# and complex solutions it's almost impossible to understand both how your app work and to run it

**Comment by gus33000** [comment]
I think you're the person from said twitter thread.... https://twitter.com/cl_ement05/status/1358143359500447745

You took a wrong turn, you downloaded the source code, instead of downloading the actual binaries, available here: https://github.com/gus33000/UUPMediaCreator/releases/tag/0.3.0.1

**Comment by cl-ement05** [comment]
ohhh I am so sorry I didn't find the actual binary. So I was trying to figure out how I should build this source code though VS. Thanks ;)
