### ISSUE TITLE
Latest (0.3.0.2) release gets flagged as a virus by Windows Defender again

### ISSUE THREAD

**Issue by riverar** [gus33000/UUPMediaCreator#18]
Trojan:Win32/Tisifi.RA!MTB
Security intelligence version: 1.331.2309.0

Submitted to Microsoft Security Intelligence again
dfbf4e37-fc2e-4b4f-80c6-398d0cd3c61f

**Comment by riverar** [comment]
Microsoft has fixed this again.

```
We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
```

**Comment by Tekkie-Boy** [comment]
Hello Rafael,

I followed the steps, Windows Defender is still blocking the download.

![Screenshot 2021-03-05 080724](https://user-images.githubusercontent.com/57283367/110079965-1cf96f80-7d8a-11eb-86b1-501175134d26.png)


![Screenshot 2021-03-05 080644](https://user-images.githubusercontent.com/57283367/110079980-2256ba00-7d8a-11eb-8959-e7daaa1638d7.png)

Best regards
