### ISSUE TITLE
0.3.0.3, SKU not reporting

### ISSUE THREAD

**Issue by Brandon621** [gus33000/UUPMediaCreator#21]
The tool is not reporting the SKU its saying bad format and no value with the Command Prompt (cmd.exe)

**Comment by Brandon621** [comment]
Windows 10 latest version

**Comment by gus33000** [comment]
What "sku reporting"? 
What do you mean? 
Any console log? 
Any repro command line? 
What argument are you running the tool with? 
What OS version?

**Comment by Brandon621** [comment]
the -s --reporting-sku argument

**Comment by gus33000** [comment]
Yes, but what argument are you passing?

**Comment by Brandon621** [comment]
uupdownload

**Comment by gus33000** [comment]
What is the full command line you are passing? that's just the tool name..

**Comment by Brandon621** [comment]
uupdownload -s --reporting-sku

**Comment by gus33000** [comment]
That command is not complete, and not valid. Refer to the help documentation available in the tool by running "uupdownload --help" to know how to use it.
