### ISSUE TITLE
Problems with relative paths when extracting cabinets

### ISSUE THREAD

**Issue by superkid200** [gus33000/UUPMediaCreator#22]
The Media Converter CLI crashes at times with nonsense exceptions for me.
After using the UUPDownload tool and when the converter said unpacking, it threw this exception:
`System.IO.DirectoryNotFoundException: Could not find a part of the path <path to specified folder>\<build full name>\<path to the CAB>` (for example: `C:\Users\[withheld]\Downloads\UUPMediaCreator\10.0.19041.867.vb_release_svc_prod1.210226-1354_amd64fre_589cf0a736db\10.0.19041.867.vb_release_svc_prod1.210226-1354_amd64fre_589cf0a736db\FeaturesOnDemand\neutral\cabs\Microsoft-Windows-UserExperience-Desktop-Package~31bf3856ad364e35~amd64~~.cab` (notice how `10.0.19041.867.vb_release_svc_prod1.210226-1354_amd64fre_589cf0a736db` is repeated).

When I created the second `10.0.19041.867.vb_release_svc_prod1.210226-1354_amd64fre_589cf0a736db`, it showed me this:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaCreationLib.MediaCreator.HandleEditionPlan(EditionTarget targetEdition, String UUPPath, String MediaPath, String LanguageCode, String InstallWIMFilePath, String WinREWIMFilePath, CompressionType CompressionType, String VHDMountPath, String CurrentBackupVHD, ProgressCallback progressCallback)
   at MediaCreationLib.MediaCreator.CreateISOMediaAdvanced(String ISOPath, String UUPPath, String LanguageCode, Boolean IntegrateUpdates, CompressionType CompressionType, ProgressCallback progressCallback)
   at UUPMediaConverterCli.Program.Main(String[] args)`

**Comment by gus33000** [comment]
What is the command line you are passing? Make sure your path are absolute and not relative

**Comment by superkid200** [comment]
I did pass on an absolute path
My command: C:\Users\[folder]\Downloads\UUPMediaCreator\UUPMediaConverterCli.exe C:\Users\[folder]\Downloads\UUPMediaCreator\10.0.19043.867.vb_release_svc_prod1.210226-1354 C:\Users\[folder]\Downloads\win.iso en-US

**Comment by gus33000** [comment]
I am guessing then here you're talking about the second exception not the first one. Would help a lot if you had separate both into their own separate issue. I noticed from your command you are trying to generate an image with all editions converted at once, is this what you want? For this you need to have downloaded all packages and not have restricted the download with the download tool to a sku. You can specify [edition] after en-US to limit it here. If that's not what you wanted to do please try to make at least Professional this way. If this ends up working fine then we narrowed down the issue further.

**Comment by gus33000** [comment]
It would also help if the full log was provided to know at what stage you are of the conversion. Just the exception is the minimalist set of information you could provide, more info would end up being useful.

**Comment by superkid200** [comment]
Thanks, I will try that.

**Comment by superkid200** [comment]
I did not actually notice the log files. Thanks for pointing that out.

**Comment by gus33000** [comment]
> I did not actually notice the log files. Thanks for pointing that out.
> 

Sorry I should have been a bit more clear here about what I meant. The tool does not save any log file per day, but the console output is what is currently used for logging purposes. I guess adding a separate logger would help a lot here. Thank you for making me realize this. 👍 let me know how my suggestion goes.

**Comment by superkid200** [comment]
So, I tried things again and found out that this issue may be exclusive with release versions. I compiled the program from scratch and it worked fine.

**Comment by gus33000** [comment]
A workaround was added yesterday, closing this issue as a result.
