### ISSUE TITLE
UEFI support issue with certain configurations

### ISSUE THREAD

**Issue by superkid200** [gus33000/UUPMediaCreator#28]
The Windows 10 ISOs I created using UUPMediaConverterCli does not boot correctly under UEFI. The tool returned no errors.

**Comment by gus33000** [comment]
What build did you make an ISO of? My isos boot fine under EFI, might be a build specific problem.

**Comment by gus33000** [comment]
https://github.com/gus33000/UUPMediaCreator/blob/master/src/MediaCreationLib.NET/CDImage/cdimage.cs#L22

As you can see here the right bootdata is being passed, and I can confirm ISOs boot fine under Hyper-V EFI (Gen 2 VM)

**Comment by superkid200** [comment]
I downloaded build 20241. It seems that older builds have this issue.
