### ISSUE TITLE
Problem stayed

### ISSUE THREAD

**Issue by truefriend-cz** [gus33000/UUPMediaCreator#30]
Please reopen https://github.com/gus33000/UUPMediaCreator/issues/29
and delete this.
(I don't know if it shows you when someone reacts to closed tickets, so I write it here. I'm sorry if you know about this.)

**Comment by gus33000** [comment]
See https://github.com/gus33000/UUPMediaCreator/issues/29#issuecomment-841799605 What you reported is unrelated to your first issue, as a result i'm closing this. And yes we can see when people comment on closed tickets
