### ISSUE TITLE
UUPMediaCreatorPackage_3.0.6.0_Test.zip cannot be installed

### ISSUE THREAD

**Issue by yoshiask** [gus33000/UUPMediaCreator#40]
The GitHub Release for version 0.3.0.6 (packaged) cannot be installed because the ZIP does not include the test certificate, and the package itself is not signed with a trusted cert.

> Error: No certificate found in the script directory.  Please make sure the certificate used to sign the package or bundle you are installing is placed in the same directory as this script.

![image](https://user-images.githubusercontent.com/7549325/118715061-caf0b380-b7e8-11eb-831b-fd4b8ab78435.png)

**Comment by Tekkie-Boy** [comment]
Make a right click on the UUPMediaCreatorPackage_3.0.6.0_xxxx.msixbundle Package what you want to install.
Then open the "**Digital Signatures**" Tab, click on "**gmonce**", then on "**Details**", in the new Window on "**View Certificat**" and then on "**Install Certificate**". 

In the Certificate Import Wizard Window click on "**Local Machine**", then on "**next**" and after that select the option "**Place all certificates in the following store**" and browse to "**Trusted Root Certification Authorities**" and when done on "**next**" again and then on "**Finish**". 

![Screenshot 2021-05-18 223231](https://user-images.githubusercontent.com/57283367/118719654-07440400-b829-11eb-98a1-c5250231b1aa.jpg)

**Comment by gus33000** [comment]
You probably want to use Trusted People instead of Trusted Root CAs by the way.

**Comment by Tekkie-Boy** [comment]
That makes more sense.
Thanks for the hint.

**Comment by yoshiask** [comment]
> Make a right click on the UUPMediaCreatorPackage_3.0.6.0_xxxx.msixbundle Package what you want to install.
> Then open the "**Digital Signatures**" Tab, click on "**gmonce**", then on "**Details**", in the new Window on "**View Certificat**" and then on "**Install Certificate**".
> 
> In the Certificate Import Wizard Window click on "**Local Machine**", then on "**next**" and after that select the option "**Place all certificates in the following store**" and browse to "**Trusted Root Certification Authorities**" and when done on "**next**" again and then on "**Finish**".
> 
> When the package is installed you can remove the certificate.
> 
> ![Screenshot 2021-05-18 223231](https://user-images.githubusercontent.com/57283367/118719654-07440400-b829-11eb-98a1-c5250231b1aa.jpg)

This is a workaround, not a solution. Why isn't the cert in the root directory, like Visual Studio does by default?

**Comment by Tekkie-Boy** [comment]
Neither did I claim it was a solution.

**Comment by gus33000** [comment]
> This is a workaround, not a solution. Why isn't the cert in the root directory, like Visual Studio does by default?

The signing process of the application is done after CI builds it, hence the lack of certificate file alongside the msixbundle. But a certificate file is always embedded with msixbundle files when signed, so it isn't really a requirement for us to deliver that file to you considering you do actually have it. It's just more convenient in the end. For future releases (considering the front end was pulled due to long path name issues) I will try to remember to place a certificate file with the folder, but it isn't really required from my point of view.
