### ISSUE TITLE
UWP App: An error occured while creating setup media.

### ISSUE THREAD

**Issue by Tekkie-Boy** [gus33000/UUPMediaCreator#42]
Host-PC:
Windows Version 19043.985 and Windows 21382.1
On both Windows versions the same failure.
As a test, I also selected version 20h2 19042.985 to create. 
This is also where this error occurs.
How can i log the process in the UWP app?

Steps to produce the error:
![Step 1](https://user-images.githubusercontent.com/57283367/118730652-462d8600-b838-11eb-84b5-e58d4f79534c.png)
![Step 2](https://user-images.githubusercontent.com/57283367/118730660-488fe000-b838-11eb-81e8-42b9c3ec11e7.png)
![Step 3](https://user-images.githubusercontent.com/57283367/118730671-4a59a380-b838-11eb-8e74-06a1529b2ce5.png)
![Step 4](https://user-images.githubusercontent.com/57283367/118730688-4c236700-b838-11eb-95e9-c1f1e09842af.png)
![Step 5](https://user-images.githubusercontent.com/57283367/118730703-4ded2a80-b838-11eb-9987-5234e62b6d1e.png)
![Step 6](https://user-images.githubusercontent.com/57283367/118731756-6447b600-b839-11eb-890a-20929664f7f2.jpg)

**Comment by gus33000** [comment]
Hi, thank you for reporting this, i've seen this happening lately with the gui, but it doesn't happen with the CLI. I'm in the process of adding logging to the GUI (app got brought up recently only). Would you be able to test the CLI to see if that works for you or not as well? I'm guessing it is going to work just fine but who knows.

**Comment by gus33000** [comment]
Upon further inspection looks like the issue happens due to long path name issues.

**Comment by Tekkie-Boy** [comment]
Hello

You are right. The ISO was created with the CLI without any problems. 
Perhaps it would be possible that at first only a log file is written during the process, which can be called up and added to the bug report?
What also has to be added is that the tmp folder with the downloaded files is cleaned up if an error has occurred. 
If I try to create the same ISO with the program again, it will download the files again.
Otherwise a lot of memory is used in the AppData Local Packages path.
