### ISSUE TITLE
macOS Font Color legibility issue

### ISSUE THREAD

**Issue by dongle-the-gadget** [gus33000/UUPMediaCreator#50]
The font color is not very legible when Light mode is on.
<img width="682" alt="Screen Shot 2021-05-21 at 16 49 02" src="https://user-images.githubusercontent.com/29563098/119118647-a26cf180-ba54-11eb-90c3-5f284e891606.png">

**Comment by gus33000** [comment]
Thanks for reporting this, triaging this now

**Comment by gus33000** [comment]
Fixed in https://github.com/gus33000/UUPMediaCreator/releases/tag/v0.3.0.8
