### ISSUE TITLE
UUPMediaCreator Error

### ISSUE THREAD

**Issue by Alee14** [gus33000/UUPMediaCreator#52]
Hello, when I tried running `./UUPMediaConverterCli 10.0.19043.985.vb_release_svc_prod1.210428-1722_arm64fre_0b6af3317c94 out.iso en-us Professional`, it seemed to give me this result.
```
[17:44:36][Information] [ReadingMetadata] File UUP/Desktop/editionpackages/en-us/Client/Microsoft-Windows-Client-LanguagePack-Package_en-us~31bf3856ad364e35~arm64~en-us~.esd is missing
[17:44:36][   Error   ] An error occured!
[17:44:36][   Error   ] An error occurred while handling edition plan for the following edition: Professional
```
`UUP/Desktop/editionpackages/en-us/Client/Microsoft-Windows-Client-LanguagePack-Package_en-us~31bf3856ad364e35~arm64~en-us~.esd` does exist on my system though

![Screenshot_20210523_174901](https://user-images.githubusercontent.com/11698947/119277710-2a86fe80-bbef-11eb-8247-7effab9fbfc1.png)

Running on Arch Linux x64
Full output: [out.txt](https://github.com/gus33000/UUPMediaCreator/files/6528964/out.txt)

**Comment by Alee14** [comment]
Nevermind about this issue, I have fixed it

**Comment by Lumiamobile68** [comment]
can you share the solution to thid problem please "An error ocurred while handling edition plan photo the following edition profesional"

**Comment by Alee14** [comment]
That was a few years ago, don't really think I really remember that :P
