### ISSUE TITLE
Enterprise LTSC

### ISSUE THREAD

**Issue by chmistj** [gus33000/UUPMediaCreator#53]
Hi, is it possible to download and create Enterprise LTSC image using this tool?

**Comment by superkid200** [comment]
I do not think so because to my knowledge, new LTSC versions are not available in Windows Update. It's the same deal with Windows versions that use the Legacy Lifecycle Policy.

**Comment by gus33000** [comment]
As @superkid200 said, LTSC versions are not delivered in windows update, neither are the components required to make them, so no it's not possible.

Although the main point of LTSC is to have a long term release supported, so i fail to understand why you would need newer versions than what Microsoft currently provides
