### ISSUE TITLE
No GUI on Windows zip's

### ISSUE THREAD

**Issue by michalpustelnik7209** [gus33000/UUPMediaCreator#56]
I tried to launch GUI version but no GUI-based app. Only console-based app.

**Comment by XenoPanther** [comment]
I believe the GUI has been removed right now due to how buggy it is.

**Comment by superkid200** [comment]
The GUI is not included with 0.3.0.6. You can download it in Actions but you might need to sign the package yourself.

**Comment by michalpustelnik7209** [comment]
Can you please send to my email for instructions?
Here is my email: ***@***.***

**Comment by superkid200** [comment]
The download links are available at https://github.com/gus33000/UUPMediaCreator/actions/runs/887781735.

I heard SignTool would be able to sign the MSIX, but I have not gotten it to work.

**Comment by gus33000** [comment]
The GUI is indeed not available for now due to long path name issues. Signtool can indeed sign the package if you want but the app will not work. Microsoft has documentation on how to do this: https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool
