### ISSUE TITLE
Exit without errors

### ISSUE THREAD

**Issue by marohinmark** [gus33000/UUPMediaCreator#59]
![image](https://user-images.githubusercontent.com/70785816/122659305-27653b00-d1ba-11eb-8920-7b6d5890d474.png)

**Comment by 1858030008** [comment]
> ![image](https://user-images.githubusercontent.com/70785816/122659305-27653b00-d1ba-11eb-8920-7b6d5890d474.png)
> 
> 

Try general command

**Comment by marohinmark** [comment]
What is 'general command'?

**Comment by gregdnls1** [comment]
Same issue. Anyone figured this out?

**Comment by gus33000** [comment]
You're using an older version of the tool. Update to the latest one. Further more, what you're trying to download has been removed from Microsoft Windows Update servers, indefinitely. Sorry.
