### ISSUE TITLE
Feature Request: Possibility to create ISO from Server ARM64 Files

### ISSUE THREAD

**Issue by excelsi** [gus33000/UUPMediaCreator#76]
Would be nice if UUP Media Converter could create ISOs from Server ARM64 ESD/CABs like:
https://uupdump.net/findfiles.php?id=f89f76c0-89f5-44db-9723-9b6e850ad504

Thanks!

**Comment by gus33000** [comment]
Hi

The tool is already able to create server media, however the update you linked (as with all public updates appearing on UUP Dump) do not contain files to make server media, therefore it is impossible to do.

What these updates are for is basically just the Cumulative Package for server.

Sorry that this isn't really what you thought it was, but the day microsoft pushes real server updates rest assured the tool will likely work, and we'll probably fix issues if any arise.

Thanks for your interest though!

**Comment by excelsi** [comment]
Thanks!
