### ISSUE TITLE
Cannnot Download x86 Version Of Windows 10 UUP Ver. 1809

### ISSUE THREAD

**Issue by TheCloudzDev** [gus33000/UUPMediaCreator#83]
Hello.

Can Someone Help Me?
I am using CLI Version UUPMediaCreator.
I am Trying To Download x86 Version Of Windows 10 UUP Ver. 1809

This Is My Command:
uupdownload.exe -s Professional -v 10.0.17763.1 -r External -c rs5_release -e EnterpriseS -l en-us -t i386

When I Execute It It Shows Me An error:
Option 't, machine-type' is defined with a bad format.
  Required option 't, machine-type' is missing.

How I Can fix it?

My OS Is Windows 11 Stable

**Comment by gus33000** [comment]
Use ```x86``` instead of ```i386```

**Comment by TheCloudzDev** [comment]
Thx i get it to working :)
