### ISSUE TITLE
Improvements expected in future releases

### ISSUE THREAD

**Issue by Gaoyifei1011** [gus33000/UUPMediaCreator#87]
Improvements expected in future releases
希望在未来的版本中得到的改进

1.希望能够添加多语言支持，能够将该应用翻译为简体中文。如果您的团队对翻译简体中文有困难，我非常乐意帮助你们翻译到简体中文。
Hope to add multilingual support and be able to translate the app into Simplified Chinese.If your team has difficulty translating into Simplified Chinese, I would be happy to help you translate into simplified Chinese.

2.希望能够在下载UUP文件和合并ISO镜像的时候可以自定义文件夹来存放缓存文件，目前只是存放在应用数据文件夹中。
We want to be able to customize the folder to store the cache files when downloading UUP files and merging ISO images. Currently, we only store the cache files in the application data folder.

3.希望能够像UUP官网的快捷分类一样，直接提供 最新 Dev 通道版本,最新 Beta 通道版本, 最新发布预览通道版本,公开发布的最新内部版本这几个方便快捷的选项，能够方便用户快捷选择所需要的版本。如果用户有自定义的高级版本，提供一个自定义查询页面并下载用户所需要的版本文件。
We hope to provide the latest Dev channel build, the latest Beta channel build, the latest release preview channel build, and the Latest Public Release build, just like the quick classification on UUP official website, so that users can quickly select the version they need.If the user has a custom advanced version, provide a custom query page and download the version files the user needs.
![图片](https://user-images.githubusercontent.com/49179966/144753286-4b36c722-289a-4ac8-91e3-48284ebe9b6b.png)

**Comment by noka0206** [comment]
No. He cannot speak Chinese. and he will be hard if he translate all of texts.

**Comment by Gaoyifei1011** [comment]
好吧。如果你们添加了多语言支持并在readme.md主页中标记了添加多语言支持的步骤。我可以创建一个PR帮助你们翻译到简体中文
All right. If you add multilingual support and mark the steps to add multilingual support on the readme.md home page. I can create a PR to help you translate into Simplified Chinese

**Comment by noka0206** [comment]
2. You have to use CLI instead of UWP for 2

**Comment by noka0206** [comment]
And this is not issue. You have to write this in Pull request Tab for this.

**Comment by Gaoyifei1011** [comment]
关于语言的翻译应该是和PR相关。但是我还提交了其他的另外两个问题，希望能解决一下。
The translation of language should be related to PR. But I also submitted two other questions that I hope can be solved.
